### PR TITLE
add outline of gao mateer

### PR DESCRIPTION
**Pull request by drahnr**
Since we have the huge upfront cost of the full walsh domain for the novel poly, the approach for gao mateer is definitely advantageous for `n <= 1024` despite the big O notation being `O(n * lg n  * lg n)` for `n = 2^m` and m _not_ being a power of 2 (which we have, but the current impl does not require). The variant for m being a power of two can achieve `O(n * lg n * lg lg n)` which for 1000 validators should provide us with an order of magnitude speedup. 

Next steps:

* [ ] Make it compile
* [ ] Obtain the `t` for our given generator polynomial 
* [ ] Impl the m is a power of 2
* [ ] Compare perf with @siddharthsinghal 's improve novel poly impl

### CODE REVIEW

**Comment by sandreim** [comment]
@drahnr any plans to merge this ?

**Comment by drahnr** [comment]
I'd like to, but realistically speaking 2023 is not happening

**Comment by vstakhov** [comment]
Will it be useful to use blas for multiplication acceleration? The one drawback I can clearly see is that it requires C/Fortran library dependency. On the other hand, it seems that there is no better way to do something like vector/matrices operations (e.g. multiplication).

**Comment by drahnr** [comment]
It's not that trivial, since it's a finite extension fields. Note that it's also unrelated to this particular algorithm

**Pull request closed without merging**
