### PR TITLE
release: 1.0.1

### PR DESCRIPTION
**Pull request by drahnr**

### CODE REVIEW

**Comment by drahnr** [comment]
@ordian if you could merge this, it's already on crates-io

**Comment by drahnr** [comment]
actually it's already borked, since the changes would not reflect the state on crates-io, we'd have to yank 1.0.1 and release 1.0.2

**Comment by ordian** [comment]
With no CI checks in this repo (#13), I would need to know which commands should I run locally to ensure everything builds and runs correctly.

**Comment by drahnr** [comment]
Tbh  I'd like to take care of the CI, it's already set up, just for my fork https://ci.spearow.io/teams/main/pipelines/reed-solomon due to the lack of permissions on this one.

**Comment by ordian** [comment]
Published 1.0.2 as you requested in https://github.com/paritytech/reed-solomon-novelpoly/pull/15#issuecomment-1720031758 in #17.

**Pull request closed without merging**
